version: "3.8"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_URL=postgresql+asyncpg://derron:password@db:5432/debug2
      - JWT_SECRET_KEY=mreQquxQMuyM2ZybDUyrrXklTh1ruOLp
    volumes:
      - .:/app

  db:
    image: postgres:15  
    restart: always
    environment:
      POSTGRES_USER: derron
      POSTGRES_PASSWORD: password
      POSTGRES_DB: debug2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
