"""create money_move_oreders

Revision ID: 6102e71dd561
Revises: 532ceb44d3ae
Create Date: 2025-02-05 21:25:52.210103

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6102e71dd561"
down_revision: Union[str, None] = "532ceb44d3ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "money_move_orders",
        sa.Column("id_acc_cr", sa.Integer(), nullable=False),
        sa.Column("id_acc_db", sa.Integer(), nullable=False),
        sa.Column("amount", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("date_executed", sa.DateTime(), nullable=True),
        sa.Column("is_executed", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_acc_cr"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_acc_db"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("money_move_orders")
    # ### end Alembic commands ###
