"""create users

Revision ID: 3912768c47e1
Revises: 9f30c0c6475f
Create Date: 2025-02-10 20:55:28.819581

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3912768c47e1"
down_revision: Union[str, None] = "9f30c0c6475f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Users",
        sa.Column("telephone", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("surname", sa.String(), nullable=False),
        sa.Column("patronymic", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("service_end_date", sa.DateTime(), nullable=True),
        sa.Column("birthday", sa.Date(), nullable=False),
        sa.Column("sex", sa.String(), nullable=False),
        sa.Column("document", sa.String(), nullable=False),
        sa.Column("doc_requisites", sa.String(), nullable=False),
        sa.Column("doc_issued_by", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Users")
    # ### end Alembic commands ###
