"""Add collumns account

Revision ID: 3464609817b8
Revises: 5f01c49bf6a3
Create Date: 2025-01-31 17:12:13.822818

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3464609817b8"
down_revision: Union[str, None] = "5f01c49bf6a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "account",
        sa.Column(
            "dateOpen",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "account", sa.Column("dateClosed", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "account",
        sa.Column("description", sa.String(length=100), nullable=False),
    )
    op.add_column(
        "account", sa.Column("isActive", sa.Boolean(), nullable=False)
    )
    op.add_column("account", sa.Column("status", sa.Boolean(), nullable=False))
    op.alter_column(
        "account",
        "numAccount",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "account",
        "numAccount",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.drop_column("account", "status")
    op.drop_column("account", "isActive")
    op.drop_column("account", "description")
    op.drop_column("account", "dateClosed")
    op.drop_column("account", "dateOpen")
    # ### end Alembic commands ###
