"""delete-account

Revision ID: f505514bf29a
Revises: 3367efc3567e
Create Date: 2025-02-10 20:50:23.660902

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f505514bf29a"
down_revision: Union[str, None] = "3367efc3567e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("accounts")
    op.drop_table("currencies")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currencies",
        sa.Column(
            "str_code", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('currencies_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="currencies_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "accounts",
        sa.Column(
            "client_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "currency_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "num_account",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "date_open",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "date_closed",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "description",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column("status", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"], ["clients.id"], name="accounts_client_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["currencies.id"],
            name="accounts_currency_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="accounts_pkey"),
    )
    # ### end Alembic commands ###
