"""time last login set to nullable in client table

Revision ID: 79801eb0c991
Revises: 547f9099898a
Create Date: 2025-02-12 19:14:53.968512

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "79801eb0c991"
down_revision: Union[str, None] = "547f9099898a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clients", "last_login_ip", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clients", "last_login_ip", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
