"""delete

Revision ID: 3367efc3567e
Revises: 265ff2248150
Create Date: 2025-02-10 20:45:02.797048

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3367efc3567e"
down_revision: Union[str, None] = "265ff2248150"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("money_move_orders")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "money_move_orders",
        sa.Column(
            "id_acc_cr", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "id_acc_db", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "amount",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "date_created",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "date_executed",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "is_executed", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "description",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["id_acc_cr"],
            ["accounts.id"],
            name="money_move_orders_id_acc_cr_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["id_acc_db"],
            ["accounts.id"],
            name="money_move_orders_id_acc_db_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="money_move_orders_pkey"),
    )
    # ### end Alembic commands ###
