"""delete-client

Revision ID: fdebc13b74a2
Revises: f505514bf29a
Create Date: 2025-02-10 20:51:32.473463

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fdebc13b74a2"
down_revision: Union[str, None] = "f505514bf29a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("clients")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column(
            "telephone", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "surname", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "patronymic", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "service_end_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("birthday", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("sex", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "document", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "doc_requisites", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "doc_issued_by", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="clients_pkey"),
    )
    # ### end Alembic commands ###
