"""account-client foreign key

Revision ID: 3eebdd067fe9
Revises: eefcb4d33cbb
Create Date: 2025-01-31 17:41:23.676527

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3eebdd067fe9"
down_revision: Union[str, None] = "eefcb4d33cbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts", sa.Column("client_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "accounts", "clients", ["client_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "accounts", type_="foreignkey")
    op.drop_column("accounts", "client_id")
    # ### end Alembic commands ###
