"""Change names

Revision ID: eefcb4d33cbb
Revises: be7883840ded
Create Date: 2025-01-31 17:31:31.118361

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "eefcb4d33cbb"
down_revision: Union[str, None] = "be7883840ded"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("numAccount", sa.String(length=50), nullable=False),
        sa.Column(
            "dateOpen",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("dateClosed", sa.DateTime(), nullable=True),
        sa.Column("description", sa.String(length=100), nullable=False),
        sa.Column("isActive", sa.Boolean(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "clients",
        sa.Column("telephone", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("surname", sa.String(), nullable=False),
        sa.Column("patronymic", sa.String(), nullable=True),
        sa.Column(
            "createdAt",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("serviceEndDate", sa.DateTime(), nullable=True),
        sa.Column("birthday", sa.Date(), nullable=False),
        sa.Column("sex", sa.String(), nullable=False),
        sa.Column("document", sa.String(), nullable=False),
        sa.Column("docRequisites", sa.String(), nullable=False),
        sa.Column("docIssuedBy", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "currencies",
        sa.Column("str_code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("client")
    op.drop_table("account")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column(
            "numAccount",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "dateOpen",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "dateClosed",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "description",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "isActive", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column("status", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="account_pkey"),
    )
    op.create_table(
        "client",
        sa.Column(
            "telephone", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "surname", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "patronymic", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "createdAt",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "serviceEndDate",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("birthday", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("sex", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "document", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "docRequisites", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "docIssuedBy", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="client_pkey"),
    )
    op.drop_table("currencies")
    op.drop_table("clients")
    op.drop_table("accounts")
    # ### end Alembic commands ###
