"""account-currency foreign key

Revision ID: bd2453dc528d
Revises: 3eebdd067fe9
Create Date: 2025-01-31 17:50:15.187942

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bd2453dc528d"
down_revision: Union[str, None] = "3eebdd067fe9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts", sa.Column("currency_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        None, "accounts", "currencies", ["currency_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "accounts", type_="foreignkey")
    op.drop_column("accounts", "currency_id")
    # ### end Alembic commands ###
